pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the source code from the repository
                git 'https://github.com/SAIKIRANN226/Terraform.git'  // Replace with your repository URL
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                    // Initialize Terraform
                    sh '''
                    cd variables
                    terraform init -reconfigure
                    '''
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    // Run Terraform plan to review the changes before applying
                    sh '''
                    cd variables
                    terraform plan
                    '''
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    // Apply Terraform configuration to create the EC2 instance
                    sh '''
                    cd variables
                    terraform apply -auto-approve
                    '''
                }
            }
        }
    }
}
